### PR TITLE
diaspy.models.Notification.when() use the create_at json field instea…

### PR DESCRIPTION
**Pull request by cnngimenez**
…d looking into the HTML code.

Patching what I told you at issue marekjm/diaspy#19

Using `created_at` json attribute is correct? Returns something like:

```
2015-05-23T09:07:21.000Z: A ***** y ***** les ha gustado tu Vuelto a compartir por ****.
```

### CODE REVIEW

**Comment by marekjm** [comment]
Looks good.

If you would format string extracted from JSON to look exactly like the one from `note_html` so that we maintain compatibility with older code I will merge your commits in.

**Comment by cnngimenez** [comment]
This is strange... dates in `note_html` looks exactly de same as the JSON one: it uses dates in ISO format ( I think it is [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) ).

Tell me what do you want me to implement:

* What the regexp models.Notification._when_regexp says: `YEAR-MONTH-DAY HOUR:MIN:SEC UTC` (Example: `2015-05-31 21:42:00 UTC`).
* Leave it because is the same as `note_html`. `%FT%TZ` according to the C strtime or its equivalent: `"%Y-%m-%dT%H:%M:%SZ`.
* Change it to another format I don't know... (Tell me which one!)

I think I can change it using datetime package (I think is the most robust way) or using string manipulation.

**Comment by cnngimenez** [comment]
Ops... Sorry... clicked accidentaly on "Close and comment" button! ... reopening now!!!

**Comment by marekjm** [comment]
Oh, well. OK then. I somehow managed to tell they are both in different formats but that wouldn't make any sense. I'll merge your commit in.

**Comment by marekjm** [comment]
Thanks. Merged in 72a1545571c58ada85f4c6f2589035a157deea60.

**Pull request merged**
